# Generated by Django 3.2.3 on 2021-06-01 06:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_cuenta', models.CharField(max_length=20)),
                ('saldo', models.DecimalField(decimal_places=3, max_digits=20)),
                ('es_activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=3, unique=True)),
                ('descripcion', models.CharField(max_length=120)),
                ('es_activo', models.BooleanField(default=True)),
                ('es_principal', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
                'ordering': ['codigo', 'es_activo'],
            },
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_operacion', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=3, max_digits=20)),
                ('fecha_operacion', models.DateTimeField(default=datetime.datetime(2021, 6, 1, 6, 11, 21, 793790, tzinfo=utc), verbose_name='Fecha operacion')),
                ('ip_operacion', models.CharField(max_length=15)),
                ('cuenta_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='destino_operacion', to='challenge.cuenta')),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='origen_operacion', to='challenge.cuenta')),
            ],
            options={
                'ordering': ['-fecha_operacion'],
            },
        ),
        migrations.AddField(
            model_name='cuenta',
            name='moneda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challenge.moneda'),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='TipoCambio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equivalencia', models.DecimalField(decimal_places=3, max_digits=20)),
                ('fecha', models.DateField()),
                ('moneda', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challenge.moneda')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('moneda', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=datetime.datetime(2021, 6, 1, 6, 11, 21, 794686, tzinfo=utc), verbose_name='Fecha movimiento')),
                ('es_abono', models.BooleanField(default=True)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challenge.cuenta')),
                ('operacion', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='challenge.operacion')),
            ],
            options={
                'ordering': ['-fecha'],
                'unique_together': {('cuenta', 'operacion')},
            },
        ),
    ]
