# Generated by Django 3.2.3 on 2021-06-02 03:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 3, 22, 11, 532054, tzinfo=utc), verbose_name='Fecha movimiento'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='fecha_operacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 3, 22, 11, 531244, tzinfo=utc), verbose_name='Fecha operacion'),
        ),
        migrations.AlterUniqueTogether(
            name='movimiento',
            unique_together=set(),
        ),
    ]
