# Generated by Django 3.2.3 on 2021-06-02 03:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0002_auto_20210602_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 3, 23, 13, 667107, tzinfo=utc), verbose_name='Fecha movimiento'),
        ),
        migrations.AlterField(
            model_name='movimiento',
            name='operacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='challenge.operacion'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='fecha_operacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 3, 23, 13, 666337, tzinfo=utc), verbose_name='Fecha operacion'),
        ),
        migrations.AlterUniqueTogether(
            name='movimiento',
            unique_together={('operacion', 'cuenta')},
        ),
    ]
