# Generated by Django 3.2.3 on 2021-06-02 22:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('challenge', '0005_auto_20210602_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimiento',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 22, 5, 36, 285627, tzinfo=utc), verbose_name='Fecha movimiento'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='fecha_operacion',
            field=models.DateTimeField(default=datetime.datetime(2021, 6, 2, 22, 5, 36, 284846, tzinfo=utc), verbose_name='Fecha operacion'),
        ),
    ]
